# Generated by Django 4.2.3 on 2023-07-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listamal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bimar', models.CharField(max_length=300)),
                ('Age', models.IntegerField()),
                ('Doctor', models.CharField(max_length=300)),
                ('ProfBihooshi', models.CharField(max_length=300)),
                ('Typeamal', models.CharField(max_length=300)),
                ('Otagh', models.CharField(max_length=300)),
                ('Scrub', models.CharField(max_length=300)),
                ('Circuler', models.CharField(max_length=300)),
                ('KarshenasBihooshi', models.CharField(max_length=300)),
                ('KarshenasOtasghamal', models.CharField(max_length=300)),
                ('Time', models.CharField(max_length=300)),
                ('Olaviat', models.CharField(choices=[('اورژانسی', 'اورژانسی'), ('پرخطر', 'پرخطر'), ('آسیب پذیر', 'آسیب پذیر'), ('عفونی', 'عفونی'), ('الکتیو', 'الکتیو')], max_length=300)),
                ('Status', models.CharField(max_length=300)),
            ],
        ),
    ]
