# Generated by Django 4.2.3 on 2023-07-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listamal',
            name='Age',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='listamal',
            name='Bimar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='listamal',
            name='Circuler',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='listamal',
            name='Doctor',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='listamal',
            name='KarshenasBihooshi',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='listamal',
            name='KarshenasOtasghamal',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='listamal',
            name='Olaviat',
            field=models.CharField(blank=True, choices=[('اورژانسی', 'اورژانسی'), ('پرخطر', 'پرخطر'), ('آسیب پذیر', 'آسیب پذیر'), ('عفونی', 'عفونی'), ('الکتیو', 'الکتیو')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='listamal',
            name='Otagh',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='listamal',
            name='ProfBihooshi',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='listamal',
            name='Scrub',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='listamal',
            name='Status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='listamal',
            name='Time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='listamal',
            name='Typeamal',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
